import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import ProjectBrief from '../components/ProjectBrief'
import Showcase from '../components/Showcase'
import Tribute from '../components/Tribute'

export default function Home() {
  return (
    <div className='w-screen h-full bg-black'>
      {/* <Head>
        <title>Body Plans for the New Millennium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Header />
      <Showcase className="pt-10" />
      <ProjectBrief />
      <Tribute />
      {/* <footer className=''>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className=''>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
